Add a testcase for local reporter path
glenjamin/mocha-multi pull request #66
Opened 2019-08-23 01:48 UTC by just-boris

Full reproducible example for #65

2019-08-23 01:53 UTC, just-boris commented
UPD: the commit bc31ced1a24840eac09ca54b72803c00b275775b also contains the fix

2019-08-23 06:16 UTC, glenjamin requested changes
The fix makes sense.

Could you leave the `mocha-multi.js` file where it was, and add the dummy reporter to the `verify` script at the bottom too?

2019-08-23 14:51 UTC, just-boris commented
This won’t work unfortunately. If mocha-multi.js stays at the top level it will not reproduce the issue. The CWD and the location of mocha-multi.js file will match and `require('./fixtures/dummy-reporter.js')` will be working without the fix.

So the point of the change is to split the location of the file and working directory

2019-08-24 05:06 UTC, glenjamin commented
Aha, I see! That wasn’t obvious to me but it does make sense now

2025-01-07 20:59 UTC, closed without merging